import { LanguagePair } from '@/src/types';

const BASE = 'https://sgjpzbpoxhqgwlnwgvcv.supabase.co/storage/v1/object/public/dictionaries';

export const LANGUAGE_PAIRS: LanguagePair[] = [
  {
    code: 'en',
    nameCs: 'Angličtina',
    nameNative: 'English',
    adjectiveCs: 'anglické',
    flag: '🇬🇧',
    sourceDb: { dbCode: 'ces-eng', headwordCount: 488, dbSizeBytes: 69632, dbUrl: `${BASE}/ces-eng.db` },
    targetDb: { dbCode: 'eng-ces', headwordCount: 150004, dbSizeBytes: 17813504, dbUrl: `${BASE}/eng-ces.db` },
  },
  {
    code: 'de',
    nameCs: 'Němčina',
    nameNative: 'Deutsch',
    adjectiveCs: 'německé',
    flag: '🇩🇪',
    sourceDb: { dbCode: 'ces-deu', headwordCount: 17730, dbSizeBytes: 5054464, dbUrl: `${BASE}/ces-deu.db` },
    targetDb: { dbCode: 'deu-ces', headwordCount: 19866, dbSizeBytes: 9752576, dbUrl: `${BASE}/deu-ces.db` },
  },
  {
    code: 'fr',
    nameCs: 'Francouzština',
    nameNative: 'Français',
    adjectiveCs: 'francouzské',
    flag: '🇫🇷',
    sourceDb: { dbCode: 'ces-fra', headwordCount: 15265, dbSizeBytes: 4521984, dbUrl: `${BASE}/ces-fra.db` },
    targetDb: { dbCode: 'fra-ces', headwordCount: 19331, dbSizeBytes: 5210112, dbUrl: `${BASE}/fra-ces.db` },
  },
  {
    code: 'es',
    nameCs: 'Španělština',
    nameNative: 'Español',
    adjectiveCs: 'španělské',
    flag: '🇪🇸',
    sourceDb: { dbCode: 'ces-spa', headwordCount: 12308, dbSizeBytes: 3379200, dbUrl: `${BASE}/ces-spa.db` },
    targetDb: { dbCode: 'spa-ces', headwordCount: 10118, dbSizeBytes: 4358144, dbUrl: `${BASE}/spa-ces.db` },
  },
  {
    code: 'it',
    nameCs: 'Italština',
    nameNative: 'Italiano',
    adjectiveCs: 'italské',
    flag: '🇮🇹',
    targetDb: { dbCode: 'ita-ces', headwordCount: 16819, dbSizeBytes: 6041600, dbUrl: `${BASE}/ita-ces.db` },
  },
  {
    code: 'pt',
    nameCs: 'Portugalština',
    nameNative: 'Português',
    adjectiveCs: 'portugalské',
    flag: '🇵🇹',
    sourceDb: { dbCode: 'ces-por', headwordCount: 16783, dbSizeBytes: 4567040, dbUrl: `${BASE}/ces-por.db` },
  },
  {
    code: 'ru',
    nameCs: 'Ruština',
    nameNative: 'Русский',
    adjectiveCs: 'ruské',
    flag: '🇷🇺',
    sourceDb: { dbCode: 'ces-rus', headwordCount: 10296, dbSizeBytes: 3170304, dbUrl: `${BASE}/ces-rus.db` },
    targetDb: { dbCode: 'rus-ces', headwordCount: 10955, dbSizeBytes: 3928064, dbUrl: `${BASE}/rus-ces.db` },
  },
  {
    code: 'pl',
    nameCs: 'Polština',
    nameNative: 'Polski',
    adjectiveCs: 'polské',
    flag: '🇵🇱',
    targetDb: { dbCode: 'pol-ces', headwordCount: 15704, dbSizeBytes: 6770688, dbUrl: `${BASE}/pol-ces.db` },
  },
  {
    code: 'nl',
    nameCs: 'Holandština',
    nameNative: 'Nederlands',
    adjectiveCs: 'holandské',
    flag: '🇳🇱',
    sourceDb: { dbCode: 'ces-nld', headwordCount: 10383, dbSizeBytes: 2891776, dbUrl: `${BASE}/ces-nld.db` },
    targetDb: { dbCode: 'nld-ces', headwordCount: 11396, dbSizeBytes: 3964928, dbUrl: `${BASE}/nld-ces.db` },
  },
  {
    code: 'sv',
    nameCs: 'Švédština',
    nameNative: 'Svenska',
    adjectiveCs: 'švédské',
    flag: '🇸🇪',
    sourceDb: { dbCode: 'ces-swe', headwordCount: 11455, dbSizeBytes: 3158016, dbUrl: `${BASE}/ces-swe.db` },
    targetDb: { dbCode: 'swe-ces', headwordCount: 16261, dbSizeBytes: 5529600, dbUrl: `${BASE}/swe-ces.db` },
  },
  {
    code: 'fi',
    nameCs: 'Finština',
    nameNative: 'Suomi',
    adjectiveCs: 'finské',
    flag: '🇫🇮',
    sourceDb: { dbCode: 'ces-fin', headwordCount: 10505, dbSizeBytes: 2945024, dbUrl: `${BASE}/ces-fin.db` },
    targetDb: { dbCode: 'fin-ces', headwordCount: 12477, dbSizeBytes: 5951488, dbUrl: `${BASE}/fin-ces.db` },
  },
  {
    code: 'da',
    nameCs: 'Dánština',
    nameNative: 'Dansk',
    adjectiveCs: 'dánské',
    flag: '🇩🇰',
    sourceDb: { dbCode: 'ces-dan', headwordCount: 15663, dbSizeBytes: 4288512, dbUrl: `${BASE}/ces-dan.db` },
  },
  {
    code: 'no',
    nameCs: 'Norština',
    nameNative: 'Norsk',
    adjectiveCs: 'norské',
    flag: '🇳🇴',
    sourceDb: { dbCode: 'ces-nor', headwordCount: 11164, dbSizeBytes: 3059712, dbUrl: `${BASE}/ces-nor.db` },
  },
  {
    code: 'tr',
    nameCs: 'Turečtina',
    nameNative: 'Türkçe',
    adjectiveCs: 'turecké',
    flag: '🇹🇷',
    sourceDb: { dbCode: 'ces-tur', headwordCount: 15465, dbSizeBytes: 4235264, dbUrl: `${BASE}/ces-tur.db` },
  },
  {
    code: 'bg',
    nameCs: 'Bulharština',
    nameNative: 'Български',
    adjectiveCs: 'bulharské',
    flag: '🇧🇬',
    sourceDb: { dbCode: 'ces-bul', headwordCount: 16621, dbSizeBytes: 5042176, dbUrl: `${BASE}/ces-bul.db` },
  },
  {
    code: 'el',
    nameCs: 'Řečtina',
    nameNative: 'Ελληνικά',
    adjectiveCs: 'řecké',
    flag: '🇬🇷',
    targetDb: { dbCode: 'ell-ces', headwordCount: 11884, dbSizeBytes: 2514944, dbUrl: `${BASE}/ell-ces.db` },
  },
  {
    code: 'ca',
    nameCs: 'Katalánština',
    nameNative: 'Català',
    adjectiveCs: 'katalánské',
    flag: '🏴',
    sourceDb: { dbCode: 'ces-cat', headwordCount: 17052, dbSizeBytes: 4599808, dbUrl: `${BASE}/ces-cat.db` },
  },
  {
    code: 'id',
    nameCs: 'Indonéština',
    nameNative: 'Bahasa Indonesia',
    adjectiveCs: 'indonéské',
    flag: '🇮🇩',
    sourceDb: { dbCode: 'ces-ind', headwordCount: 11792, dbSizeBytes: 3301376, dbUrl: `${BASE}/ces-ind.db` },
  },
  {
    code: 'ja',
    nameCs: 'Japonština',
    nameNative: '日本語',
    adjectiveCs: 'japonské',
    flag: '🇯🇵',
    sourceDb: { dbCode: 'ces-jpn', headwordCount: 10335, dbSizeBytes: 2998272, dbUrl: `${BASE}/ces-jpn.db` },
  },
  {
    code: 'ga',
    nameCs: 'Irština',
    nameNative: 'Gaeilge',
    adjectiveCs: 'irské',
    flag: '🇮🇪',
    sourceDb: { dbCode: 'ces-gle', headwordCount: 12813, dbSizeBytes: 3584000, dbUrl: `${BASE}/ces-gle.db` },
  },
];

export const FREE_DOWNLOAD_LIMIT = 1;
